# Generated by Django 6.0.7 on 2026-07-22 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Used as the logo's alt text.", max_length=200)),
                ('logo', models.ImageField(upload_to='branding/sponsors/')),
                ('website_url', models.URLField(blank=True, help_text='Optional — makes the logo clickable.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='branding.sitesettings')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
