# Generated by Django 6.0.6 on 2026-07-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='events/covers/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text='Only used if no cover image is uploaded above.'),
        ),
    ]
