# Generated by Django 6.0.6 on 2026-07-18 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_cover_image_alter_event_cover_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='video_url',
            field=models.URLField(blank=True, help_text="YouTube link, e.g. for a past session's recap video."),
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='events.event')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
