# Generated by Django 6.0.6 on 2026-07-18 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlineup',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_entries', to='events.event'),
        ),
        migrations.AlterUniqueTogether(
            name='eventlineup',
            unique_together={('event', 'artist')},
        ),
    ]
