# Generated by Django 6.0.6 on 2026-07-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, upload_to='artists/photos/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Only used if no photo is uploaded above.'),
        ),
    ]
