# Generated by Django 6.0.6 on 2026-07-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_artist_photo_alter_artist_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='is_house_band',
            field=models.BooleanField(default=False, help_text="Constant house band member — shown on the About page. Leave unchecked for one-off guest artists added to a specific event's lineup."),
        ),
    ]
